package errors

var (
	ErrLogin                       = "Неудачная попытка аутентификации"
	ErrRegistration                = "Неудачная попытка регистрации"
	ErrUserExist                   = "Имя пользователя уже зарегистрировано"
	ErrUsernameIncorrect           = "Длинна имени пользователя должна быть не менее шести символов"
	ErrPasswordIncorrect           = "Пароль должен состоять минимум из 8 букв, 1 цифра, 1 верхний регистр, 1 специальный символ (пример: Password-123)"
	ErrPasswordDifferent           = "Пароли не совпали"
	ErrNameEmpty                   = "Название не заполнено"
	ErrTextEmpty                   = "Информация не заполнена"
	ErrDescriptionEmpty            = "Описание не заполнено"
	ErrTextExist                   = "Текст с таким названием уже существует"
	ErrLoginPasswordExist          = "Логин пароль с таким названием уже существует"
	ErrBinaryExist                 = "Файл с таким названием уже существует"
	ErrLoginEmpty                  = "Логин не заполнен"
	ErrPasswordEmpty               = "Пароль не заполнен"
	ErrCardExist                   = "Карта с таким названием уже существует"
	ErrPaymentSystemEmpty          = "Платёжная система не заполнена"
	ErrNumberEmpty                 = "Номер не заполнен"
	ErrNumberIncorrect             = "Номер некорректный (пример: 4532015112830366)"
	ErrHolderEmpty                 = "Владелец не заполнен"
	ErrEndDateEmpty                = "Действителен до не заполнен"
	ErrEndDateIncorrect            = "Действителен до некорректный (пример: 01/02/2006)"
	ErrCvcEmpty                    = "CVC не заполнен"
	ErrCvcIncorrect                = "CVC некорректный (пример: 123)"
	ErrLoginPasswordCreate         = "Ошибка при добавлении логин-пароль"
	ErrLoginPasswordUpdate         = "Ошибка при изменении логин-пароль"
	ErrTextCreate                  = "Ошибка при добавлении текста"
	ErrTextUpdate                  = "Ошибка при изменении текста"
	ErrCardCreate                  = "Ошибка при добавлении карты"
	ErrCardUpdate                  = "Ошибка при изменении карты"
	ErrSynchronization             = "Ошибка при синхронизации"
	ErrLoginPasswordTblIndexDelete = "Выберите в таблице логин-пароль, который хотите удалить"
	ErrLoginPasswordTblIndexUpdate = "Выберите в таблице логин-пароль, который хотите изменить"
	ErrTextTblIndexDelete          = "Выберите в таблице текст, который хотите удалить"
	ErrTextTblIndexUpdate          = "Выберите в таблице текст, который хотите изменить"
	ErrCardTblIndexDelete          = "Выберите в таблице карту, которую хотите удалить"
	ErrCardTblIndexUpdate          = "Выберите в таблице карту, которую хотите изменить"
	ErrUpload                      = "Ошибка при загрузке файла"
	ErrFileSize                    = "Ошибка при загрузке файла. Размер файла не должен превышать 4000000 байт. "
	ErrBinaryTblIndexDownload      = "Выберите в таблице файл, который хотите скачать"
	ErrBinaryTblIndexDelete        = "Выберите в таблице файл, который хотите удалить"
)
